### PR TITLE
Added Missing Public Functions

### PR DESCRIPTION
**Pull request by StingzLD**
Add the following functions from the Public folder to the PSMeraki.psd1 file under FunctionsToExport and CmdletsToExport:

Get-MrkRestApiVersion
Invoke-MrkRestMethod
Restart-MrkDevice
Set-MrkNetworkSiteToSiteVPN
Set-MrkRestApiVersion

### CODE REVIEW

**Comment by mdewart-springpoint** [comment]
Would love this pull request to be accepted.

**Comment by mdewart-springpoint** [comment]
@sanderkl Would also like this pull request to be accepted and that invoke-mrkrestmethod is available in the PSGallery version.

**Comment by sanderkl** [comment]
sorry to be so slow, thanks for the fix!

**Comment by StingzLD** [comment]
No problem! I had already fixed it for myself, so might as well submit the fix for all future versions for everyone.

**Pull request merged**
